### ISSUE TITLE
Working with UTC

### ISSUE THREAD

**Issue by BoboTiG** [andrewcooke/simple-date#2]
Hello,

Surprisingly (or not) this snippet works:

    day = '2016-06-01 00:00:00'
    later = SimpleDate(day).utc + timedelta(days=10)
    print(day, later)

While this one cause a `RecursionError`:

    day = '2016-06-01 00:00:00'
    later = SimpleDate(day, tz='UTC') + timedelta(days=10)
    print(day, later)

I attached the full error using `debug=True`. Did I misused something?

[trace.txt](https://github.com/andrewcooke/simple-date/files/439566/trace.txt)

**Comment by andrewcooke** [comment]
is this related to the so question?

i've already told the op that i'll try fix this this weekend.  i'll update here and on so when it's fixed.

**Comment by BoboTiG** [comment]
Yes it is :)
Great to read that!

**Comment by andrewcooke** [comment]
So, there were two issues here.

The first is easy to explain.  Generating a message for a certain error caused the same error it was trying to report.  That caused a new message to be generated, which caused a new error, which ... eventually exhausted the stack.  That is now fixed.

The second is harder to explain, because timezones are complicated.  So I will start by giving an example that is easier to understand.  Consider this date in PDT (Pacific Daylight Time):
```
>>> SimpleDate('2016-08-28', tz='PDT')
SimpleDate('2016-08-28')
```
if we add 6 months to that, we will be in the middle of winter.  PDT doesn't even **exist** then (it's winter)!  So we get an error:
```
>>> SimpleDate('2016-08-28', tz='PDT') + timedelta(days=180)
simpledate.SingleInstantTzError: Attempted to use PDT, defined only for 2016-08-28 07:00:00+00:00
```

Now you could argue that SimpleDate should be smart enough to know when PDT ends.  But it isn't (and afaik it just doesn't have the data available, but I may be wrong).  Instead, SimpleDate **refuses to modify dates associated with timezones that may have limited validity**.  That's what "single instant" means.

For more on this see [the documentation](https://github.com/andrewcooke/simple-date#why-did-i-get-the-error-singleinstanttzerror-).

But in this case, the timezone was UTC!  We know that is always valid.  So I have added a special case that avoids this restriction when parsing UTC:
```
>>> SimpleDate('2016-08-28', tz='UTC') + timedelta(days=180)
SimpleDate('2017-02-24', tz='UTC')
```

This is now in git.  I want to improve the docs slightly before release, and need to go out now, so the release will have to wait until later today.
